services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT:-reth}/Dockerfile
    ports:
      - "8645:8545" # RPC (changed to avoid conflict with L1)
      - "8646:8546" # websocket (changed to avoid conflict with L1)
      - "7301:6060" # metrics
      - "30303:30303" # P2P TCP
      - "30303:30303/udp" # P2P UDP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["bash", "./execution-entrypoint"]
    volumes:
      - ${HOST_DATA_DIR:-./base-data}:/data
    environment:
      - NODE_TYPE=${NODE_TYPE:-vanilla}
    env_file:
      - ${NETWORK_ENV:-.env.mainnet} # Use .env.mainnet by default, override with .env.sepolia for testnet
  node:
    build:
      context: .
      dockerfile: ${CLIENT:-reth}/Dockerfile
    depends_on:
      - execution
    ports:
      - "7545:8545" # RPC
      - "9222:9222" # P2P TCP
      - "9222:9222/udp" # P2P UDP
      - "7300:7300" # metrics
      - "6060:6060" # pprof
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["bash", "./op-node-entrypoint"]
    env_file:
      - ${NETWORK_ENV:-.env.mainnet} # Use .env.mainnet by default, override with .env.sepolia for testnet
